id: P9188E563
initial_creation_type: ocr
source_metadata:
  volumes:
    79f82218a8494d899a7f8f202e3c5489:
      base_file: v093.txt
      image_group_id: I1PD95938
      title: བསླབ་པ་བཅུའི་ཆོ་ག།
      total_pages: 1484
      volume_number: 93
